#ifndef TOOLS_H
#define TOOLS_H

#define wait_while(cond) while(cond) {}

// macro args sugar for 0-16 pins

#define FOR_EACH_1(INVOKE, X) INVOKE(X)
#define FOR_EACH_2(INVOKE, X, ...) INVOKE(X); FOR_EACH_1(INVOKE, __VA_ARGS__)
#define FOR_EACH_3(INVOKE, X, ...) INVOKE(X); FOR_EACH_2(INVOKE, __VA_ARGS__)
#define FOR_EACH_4(INVOKE, X, ...) INVOKE(X); FOR_EACH_3(INVOKE, __VA_ARGS__)
#define FOR_EACH_5(INVOKE, X, ...) INVOKE(X); FOR_EACH_4(INVOKE, __VA_ARGS__)
#define FOR_EACH_6(INVOKE, X, ...) INVOKE(X); FOR_EACH_5(INVOKE, __VA_ARGS__)
#define FOR_EACH_7(INVOKE, X, ...) INVOKE(X); FOR_EACH_6(INVOKE, __VA_ARGS__)
#define FOR_EACH_8(INVOKE, X, ...) INVOKE(X); FOR_EACH_7(INVOKE, __VA_ARGS__)
#define FOR_EACH_9(INVOKE, X, ...) INVOKE(X); FOR_EACH_8(INVOKE, __VA_ARGS__)
#define FOR_EACH_10(INVOKE, X, ...) INVOKE(X); FOR_EACH_9(INVOKE, __VA_ARGS__)
#define FOR_EACH_11(INVOKE, X, ...) INVOKE(X); FOR_EACH_10(INVOKE, __VA_ARGS__)
#define FOR_EACH_12(INVOKE, X, ...) INVOKE(X); FOR_EACH_11(INVOKE, __VA_ARGS__)
#define FOR_EACH_13(INVOKE, X, ...) INVOKE(X); FOR_EACH_12(INVOKE, __VA_ARGS__)
#define FOR_EACH_14(INVOKE, X, ...) INVOKE(X); FOR_EACH_13(INVOKE, __VA_ARGS__)
#define FOR_EACH_15(INVOKE, X, ...) INVOKE(X); FOR_EACH_14(INVOKE, __VA_ARGS__)
#define FOR_EACH_16(INVOKE, X, ...) INVOKE(X); FOR_EACH_15(INVOKE, __VA_ARGS__)

#define GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,NAME,...) NAME

#define FOR_EACH(INVOKE, ...) \
    GET_MACRO(__VA_ARGS__, \
    FOR_EACH_16, FOR_EACH_15, FOR_EACH_14, FOR_EACH_13, \
    FOR_EACH_12, FOR_EACH_11, FOR_EACH_10, FOR_EACH_9, \
    FOR_EACH_8, FOR_EACH_7, FOR_EACH_6, FOR_EACH_5, \
    FOR_EACH_4, FOR_EACH_3, FOR_EACH_2, FOR_EACH_1)(INVOKE, __VA_ARGS__)

#endif